#!/bin/bash

cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution
tmpDir=$(mkdir -p "/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/tmp.251f4e70" && echo "/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/tmp.251f4e70")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution

)
out717c6472="${tmpDir}/out.$$" err717c6472="${tmpDir}/err.$$"
mkfifo "$out717c6472" "$err717c6472"
trap 'rm "$out717c6472" "$err717c6472"' EXIT
touch '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution/stdout' '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution/stderr'
tee '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution/stdout' < "$out717c6472" &
tee '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution/stderr' < "$err717c6472" >&2 &
(
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution


cutadapt \  # -j is num cores
  --action=retain \
  --discard-untrimmed \
  -g /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/inputs/-338175371/v3_fwd_primers_1B_anchored.fasta \ #have caret to force primer search at begining of read
  -G /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/inputs/-338175371/v3_rev_primers_1B_anchored.fasta \
  --pair-adapters \
  -o untrimmed_R1.fastq.gz \
  -p untrimmed_R2.fastq.gz \
  -e 0 \
  --no-indels \
  /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/inputs/2007597314/test_S100_R1_001.fastq.gz \
  /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/inputs/2007597314/test_S100_R2_001.fastq.gz \
  > cutadapt.log


      #for dada2 no bio variation in seqs for algo
      #removeprimers from sequences for dada2
      #bc error profile in primers skews the dada2 algo

# gzcat /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/inputs/2007597314/test_S100_R1_001.fastq.gz
# gzcat /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/inputs/2007597314/test_S100_R2_001.fastq.gz
)  > "$out717c6472" 2> "$err717c6472"
echo $? > /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution
sync


)
mv /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution/rc.tmp /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/717c6472-b5aa-4411-9a2e-c77862a67586/call-cutadapt/execution/rc
