#!/bin/bash

cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution
tmpDir=$(mkdir -p "/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/tmp.79c9ffd7" && echo "/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/tmp.79c9ffd7")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution

)
out0ec110a2="${tmpDir}/out.$$" err0ec110a2="${tmpDir}/err.$$"
mkfifo "$out0ec110a2" "$err0ec110a2"
trap 'rm "$out0ec110a2" "$err0ec110a2"' EXIT
touch '/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution/stdout' '/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution/stderr'
tee '/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution/stdout' < "$out0ec110a2" &
tee '/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution/stderr' < "$err0ec110a2" >&2 &
(
cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution


echo "hello world"
)  > "$out0ec110a2" 2> "$err0ec110a2"
echo $? > /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution
sync


)
mv /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution/rc.tmp /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/myWorkflow/0ec110a2-f05c-40e6-9a9f-b42054f7ef75/call-myTask/execution/rc
