#!/bin/bash

cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution
tmpDir=$(mkdir -p "/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/tmp.bbd9a8e0" && echo "/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/tmp.bbd9a8e0")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution

)
oute5ffdca0="${tmpDir}/out.$$" erre5ffdca0="${tmpDir}/err.$$"
mkfifo "$oute5ffdca0" "$erre5ffdca0"
trap 'rm "$oute5ffdca0" "$erre5ffdca0"' EXIT
touch '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution/stdout' '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution/stderr'
tee '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution/stdout' < "$oute5ffdca0" &
tee '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution/stderr' < "$erre5ffdca0" >&2 &
(
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution


echo /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/inputs/2007597314/test_S100_R1_001.fastq.gz /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/inputs/2007597314/test_S100_R2_001.fastq.gz

# cutadapt \
#   --action=retain \
#   --discard-untrimmed \
#   -g file:$primer_f1 \
#   -G file:$primer_f2 \
#   --pair-adapters \
#   -o untrimmed_R1.fastq.gz \
#   -p untrimmed_R2.fastq.gz \
#   -e 0 \
#   --no-indels \
#   $forward_reads \
#   $reverse_reads \
#   > cutadapt.log

      # -j is num cores
      #have caret to force primer search at begining of read

      #for dada2 no bio variation in seqs for algo
      #removeprimers from sequences for dada2
      #bc error profile in primers skews the dada2 algo
)  > "$oute5ffdca0" 2> "$erre5ffdca0"
echo $? > /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution
sync


)
mv /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution/rc.tmp /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/AmplDemuxer/e5ffdca0-dfee-4aa6-8dda-305f2899cce5/call-cutadapt/execution/rc
