#!/bin/bash

cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution
tmpDir=$(mkdir -p "/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/tmp.ac12067c" && echo "/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/tmp.ac12067c")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution

)
out3c3a91c1="${tmpDir}/out.$$" err3c3a91c1="${tmpDir}/err.$$"
mkfifo "$out3c3a91c1" "$err3c3a91c1"
trap 'rm "$out3c3a91c1" "$err3c3a91c1"' EXIT
touch '/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution/stdout' '/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution/stderr'
tee '/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution/stdout' < "$out3c3a91c1" &
tee '/Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution/stderr' < "$err3c3a91c1" >&2 &
(
cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution


echo hello_world
)  > "$out3c3a91c1" 2> "$err3c3a91c1"
echo $? > /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution
sync


)
mv /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution/rc.tmp /Users/severianovillarruel/eppicenter/shed/cromwell/cromwell-executions/wf/3c3a91c1-53f3-42b9-83ac-be99db86d5a3/call-hello/execution/rc
