#!/bin/bash

cd /Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution
tmpDir=$(mkdir -p "/Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/tmp.834bdcc3" && echo "/Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/tmp.834bdcc3")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution

)
outaa24d866="${tmpDir}/out.$$" erraa24d866="${tmpDir}/err.$$"
mkfifo "$outaa24d866" "$erraa24d866"
trap 'rm "$outaa24d866" "$erraa24d866"' EXIT
touch '/Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution/stdout' '/Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution/stderr'
tee '/Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution/stdout' < "$outaa24d866" &
tee '/Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution/stderr' < "$erraa24d866" >&2 &
(
cd /Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution


echo hello_world > file.txt
)  > "$outaa24d866" 2> "$erraa24d866"
echo $? > /Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution
sync


)
mv /Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution/rc.tmp /Users/severianovillarruel/eppicenter/library/WDL/example/cromwell-executions/wf/aa24d866-f520-4f19-923d-7b7437eab164/call-hello/execution/rc
