#!/bin/bash

cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution
tmpDir=$(mkdir -p "/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/tmp.f5f1cfc2" && echo "/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/tmp.f5f1cfc2")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution

)
out59eaf1ff="${tmpDir}/out.$$" err59eaf1ff="${tmpDir}/err.$$"
mkfifo "$out59eaf1ff" "$err59eaf1ff"
trap 'rm "$out59eaf1ff" "$err59eaf1ff"' EXIT
touch '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution/stdout' '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution/stderr'
tee '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution/stdout' < "$out59eaf1ff" &
tee '/Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution/stderr' < "$err59eaf1ff" >&2 &
(
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution


gzcat /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/inputs/-759946158/test_S100_R1_001.fastq.gz
gzcat /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/inputs/-759946158/test_S100_R2_001.fastq.gz
)  > "$out59eaf1ff" 2> "$err59eaf1ff"
echo $? > /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution
sync


)
mv /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution/rc.tmp /Users/severianovillarruel/eppicenter/library/WDL/AmplDemuxer/cromwell-executions/wf/59eaf1ff-4ed5-4a38-951d-2c5a9c67cb14/call-cutadapt/execution/rc
